---
- name: Converge
  hosts: all
  vars:
    vector_config:
      sources:
        dummy_logs:
          type: "demo_logs"
          format: "syslog"
          interval: 1

      transforms:
        parse_logs:
          type: "remap"
          inputs: ["dummy_logs"]
          source: |
            . = parse_syslog!(string!(.message))

      sinks:
        print:
          type: "console"
          inputs: ["parse_logs"]
          encoding:
            codec: "json"
            json:
              pretty: true
  tasks:
    - name: "Include vector"
      include_role:
        name: "my.vector"
