---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: oracle
    image: oraclelinux:8
    pre_build_image: true
  - name: ubuntu
    dockerfile: Dockerfile.j2
    image: ubuntu:20.04
    pre_build_image: false
provisioner:
  name: ansible
verifier:
  name: ansible
